openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description: The library service

servers:
  - url: https://localhost:8080

tags:
  - name: "Library"


paths:

  /library/books:
    get:
      summary: This is summary
      tags:
        - "Library"
      description: This is a description
      operationId: getAllBooksInLibrary
      responses:
        "200":
          description: This means its ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

components:

  schemas:

    Book:
      description: This is the book model
      type: object
      properties:
        name:
          description: The name of book
          type: string
        bookAuthor:
          description: name of author
          type: string